### ISSUE TITLE
"Please read rules" banner reopens when signing in on a new computer

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/forum#15]
obviously very low priority / maybe shouldn't be fixed

signing into your account on a new computer (or in an incognito/private browser window) will show the "pls read rules" prompt again, even though it's supposed to be cached to only show new accounts who haven't acknowledged it yet.
![image](https://user-images.githubusercontent.com/62961532/120127816-65100e80-c18e-11eb-81bb-416c9312d53a.png)

**Comment by Hona** [comment]
Intended behaviour - no real work around either as it uses local storage
