### ISSUE TITLE
Usernames cannot have dots in them

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/forum#3]
Raised by zer0.k, who cannot sign up with their original nick due to it:

![image](https://user-images.githubusercontent.com/5162166/110897025-ae0ca100-82ca-11eb-898f-68f46c2a123c.png)

**Comment by Hona** [comment]
https://discuss.flarum.org/d/915-spaces-non-ascii-characters-in-usernames/42

You can change your username to allow ASCII characters by setting your display name
